coverage:
  precision: 3
  round: down
  range: "80...100"

  notify:
    gitter:
      default:
        url: https://webhooks.gitter.im/e/b688071667f9bb1d01e2

  status:
    project:
      default:
        target: 90%
        threshold: 1%
        base: auto
        set_pending: yes
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

    patch:
      default:
        target: 90%
        set_pending: yes
        base: auto
        if_no_uploads: success
        if_not_found: success
        if_ci_failed: error

    changes:
      default:
        base: auto
        set_pending: yes
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
